another test

diff --git a/.github/workflows/ci-on-macdevice.yml b/.github/workflows/ci-on-macdevice.yml
--- a/.github/workflows/ci-on-macdevice.yml
+++ b/.github/workflows/ci-on-macdevice.yml
@@ -1,4 +1,4 @@
-name: Podman Deployment CI
+name: Podman Deployment CI on Mac 
 
 on:
   push:
@@ -32,7 +32,20 @@ jobs:
       uses: juliangruber/sleep-action@v1
       with:
         time: 60s
-
+    - name: Test
+      run: |
+        set +e
+        ./miniChRIS-docker/test.sh
+        rc=$?
+        
+        # if tests fail, print out all logs
+        if [ "$rc" != '0' ]; then
+          set -x
+          for c in $(podman ps -a --format '{{ .Names }}' --filter 'name=minichris'); do
+            podman logs $c
+          done
+        fi
+        exit $rc
     - name: Pod Health Check Testing Networking
       run: |
         pwd
